# -*- coding: utf-8 -*-
"""Copy of Maral_7B_Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKV7tJnDp3mMgilSmtS1-zRe_VDcj0D5

# Maral 7B Inference Notebook

<p align="center">
 <img src="https://huggingface.co/MaralGPT/Maral-7B-alpha-1/resolve/main/maral-7b-announce.png" width=256 height=256/>
</p>

## About Maral

Maral is just a new large lanugage model, specializing on the Persian language. This model is based on Mistral and trained an Alpaca Persian dataset. This model is one of the few efforts in Persian speaking scene in order to bring our language to a new life in the era of AI.

Also, since Maral is based on Mistral, it's capable of producing English answers as well.

## Our Team

* Muhammadreza Haghiri ([Website](https://haghiri75.com/en) - [Github](https://github.com/prp-e) - [LinkedIn](https://www.linkedin.com/in/muhammadreza-haghiri-1761325b))
* Mahi Mohrechi ([Website](https://mohrechi-portfolio.vercel.app/) - [Github](https://github.com/f-mohrechi) - [LinkedIn](https://www.linkedin.com/in/faeze-mohrechi/))

## Needed libraries

Since the model is loaded in 8 bit quantization mode on free colab, you need `bitsandbytes`. If you do own a better GPU, go with full 16 bit quantization.
"""

!pip install transformers accelerate bitsandbytes -q

!pip install pandas -q

from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
import torch
import pandas as pd
from google.colab import files
import io

#مرحله آپلود فایل توسط کاربر
print("لطفاً فایل متنی (.txt) خود را انتخاب و آپلود کنید:")

# حلقه برای اطمینان از دریافت فایل txt
while True:
    uploaded = files.upload()

    if not uploaded:
        print("⚠️ هیچ فایلی آپلود نشد! دوباره تلاش کنید.")
        continue

    # نام فایل و محتوای باینری آن
    file_name = list(uploaded.keys())[0]
    file_content = uploaded[file_name]

    # بررسی پسوند فایل
    if not file_name.lower().endswith('.txt'):
        print(f"❌ فایل '{file_name}' از نوع txt نیست!")
        print("لطفاً فقط فایل‌های با پسوند .txt آپلود کنید.")
        print("دوباره تلاش کنید...\n")
        continue

    break  # اگر فایل txt بود از حلقه خارج می‌شویم

print(f"✅ فایل txt آپلود شده: {file_name}")

# خواندن محتوای فایل txt
try:
    # دیکد کردن محتوای باینری به متن
    text_content = file_content.decode('utf-8')  # یا 'utf-8-sig' برای فایل‌هایی با BOM
except UnicodeDecodeError:
    try:
        text_content = file_content.decode('utf-8-sig')
    except UnicodeDecodeError:
        text_content = file_content.decode('latin-1')  # یا encodingهای دیگر

# تقسیم متن به خطوط و حذف خطوط خالی
prompts = [line.strip() for line in text_content.split('\n') if line.strip()]

if not prompts:
    print("⚠️ هیچ متن قابل استفاده‌ای در فایل پیدا نشد!")
else:
    # تبدیل به دیتافریم
    dataset = pd.DataFrame({'prompt': prompts})

    # نمایش برای بررسی
    print(f"\n📊 تعداد پرامپت‌ها: {len(dataset)}")
    print("\n📝 ۵ مورد اول دیتاست:")
    display(dataset.head())  # در کولب بهتر نمایش می‌دهد

    # نمایش نمونه‌ای از متن‌ها
    print("\n🔍 نمونه متن‌های استخراج شده:")
    for i, prompt in enumerate(prompts[:3]):
        print(f"{i+1}. {prompt[:100]}..." if len(prompt) > 100 else f"{i+1}. {prompt}")

"""## Loading Model"""

model_name_or_id = "MaralGPT/Maral-7B-alpha-1"

model = AutoModelForCausalLM.from_pretrained(model_name_or_id, torch_dtype=torch.float16, device_map="auto", low_cpu_mem_usage=True, load_in_8bit=True)
tokenizer = AutoTokenizer.from_pretrained(model_name_or_id)

"""## Model Structure"""

model

"""### Generation Config

This cell, is a simple and easy way to tweak the configurations for text generation.
"""

generation_config = GenerationConfig(
    do_sample=True,
    top_k=1,
    temperature=0.9,
    max_new_tokens=100,
    pad_token_id=tokenizer.eos_token_id
)

"""## Prompt Format

This model, uses _Guanaco_ format, which is like this:

```
### Human: <prompt>
### Assistant: <answer>
```

So in the below cell, you can easily modify the prompt without messing with the format.
"""

# حالا حلقه روی دیتاست
outputs = []  # لیست برای ذخیره خروجی‌ها

for index, row in dataset.iterrows():
    prompt = row['prompt']  # پرامپت فعلی از دیتاست

    # اگر می‌خوای پرامپت رو فرمت کنی (مثل اضافه کردن "Human:" یا چیزی)
    formatted_prompt = f"### Human: {prompt}\n### Assistant:"

    # تبدیل به inputs
    inputs = tokenizer(formatted_prompt, return_tensors="pt").to("cuda")  # اگر GPU داری، "cuda" نگه دار

    # جنریت
    output_ids = model.generate(**inputs, generation_config=generation_config)

    # decode خروجی
    generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)

    # فقط بخش Assistant رو استخراج کن (اختیاری، بسته به فرمت)
    if "### Assistant:" in generated_text:
        generated_text = generated_text.split("### Assistant:")[1].strip()

    # ذخیره در لیست
    outputs.append({'prompt': prompt, 'response': generated_text})

    print(f"پردازش پرامپت {index+1}/{len(dataset)} تمام شد.")

# تبدیل خروجی‌ها به دیتافریم و ذخیره در فایل
with open('پاسخ‌های مدل.txt', 'w', encoding='utf-8') as f:
    for i, item in enumerate(outputs, 1):
        f.write(f"شماره {i}\n")
        f.write(f"پرامپت: {item['prompt']}\n")
        f.write(f"پاسخ : {item['response']}\n")
        f.write("\n" + "="*80 + "\n\n")

print("فایل 'پاسخ‌های مدل.txt' آماده دانلود است.")